### ISSUE TITLE
Rectify() - invalid extent

### ISSUE THREAD

**Issue by ActiveMargins** [rspatial/raster#132] opened 2020-06-14 22:26 UTC
I'm working with some ASTER satellite data. This data comes in the format of a orthorectified geotiff. By this the scene has been rotated to north and the zero values have been added to the in the void space.
Example scene -"AST_L1B_00308142007185952_20200604105240_19625.SWIR_Swath.ImageData4"
Example extent - "class      : Extent 
xmin       : 567593.4 
xmax       : 654753.7 
ymin       : 5666116 
ymax       : 5744572 "

When bringing it in to R using the raster() function, the entire raster (including void space) has had a rotation applied to it (i.e., @rotated=TRUE). I have tried to use the rectify() function, however I get the error "Error in validityMethod(object) : invalid extent: ymin >= ymax"

This problem has been run into before but not explicitly solve:
https://stackoverflow.com/questions/53507862/issue-with-rectify-on-rotated-raster-using-r-raster

**Comment by rhijmans** [comment] 2020-06-14 22:37
Can you provide an example file?

**Comment by ActiveMargins** [comment] 2020-06-14 22:51
I have added an example file to a new repository at the following link:
https://github.com/ActiveMargins/ASTERSatelliteProcessing
Sorry if sending a link to another repository is not the best form for issue reports. I cannot find an example of a GeoTIFF that is easily linked to for download. Additionally, .tif is not supported for file attachments.

**Comment by rhijmans** [comment] 2020-06-15 03:43
Thank you for your efforts. I can reproduce this error and will look at this over the coming days. 
I also checked this with `terra` and that "works", except that the min and max values, and the NODATA value are not correctly reported by the file, but that can be easily fixed (see below).

```
library(terra)
f <- "AST_L1B_00308142007185952_20200604105240_19625.SWIR_Swath.ImageData4.tif"
x <- rast(f)
z <- classify(x, cbind(0,NA))
plot(z)
```
Is this correct, or is this wrong and does this work because terra ignores the rotation?

**Comment by ActiveMargins** [comment] 2020-06-15 05:17
Thanks for the quick reply and your time. I really appreciate it. So I followed the terra workflow that you posted, exported using terra::writeRaster, however it's is not oriented the same as the original GeoTif when I bring the two into a gis (QGIS in this case). I've attached an example figure below.
![example](https://user-images.githubusercontent.com/52948432/84617835-71bc2980-ae8d-11ea-99dc-cdf7c0bcc145.JPG)
I've done the same thing using the raster package: imported using raster() and then exported using writeraster(). Its compared to original .tif loaded in the QGIS.  
![image](https://user-images.githubusercontent.com/52948432/84619422-38d28380-ae92-11ea-92f7-5e203bb26922.png)
I don't know where the CRS issue stems from. I'm happy working in either package (open to suggestions). I'm hoping to do the heavy lifting working with these data in R doing some raster calculations and transforming the data, then working more cartography of in a GIS. Again thanks for all your help.

**Comment by rhijmans** [comment] 2020-06-21 02:15
I have made some progress, by implementing `rectify` in the `terra` package . 

```
f <- "AST_rotated.tif"
library(terra)
x <- rast(f)
r <- rectify(x)
```
I later realized that this also works

````
s <- project(x, crs(x))
```

You can then either use `writeRaster` to save to file, or do `y <- raster(r)` to coerce a SpatRaster to a Raster* object.

Notes: 
the `terra` package does not yet guard against using a rotated raster as if it were not (like the raster package does), but I will implement that. 

This also needs to be fixed in the raster package --- but that has a lower priority for me.

**Comment by aloboa** [comment] 2020-07-24 11:43
Just found the same issue with an ASTER image.
When I try your workaround within raster I get:
```
> vnir
class      : RasterStack 
rotated    : TRUE
dimensions : 4200, 4980, 20916000, 3  (nrow, ncol, ncell, nlayers)
.../...
> crs(vnir)
CRS arguments:
 +proj=utm +zone=29 +datum=WGS84 +units=m +no_defs 
> test <- project(vnir[[3]],proj=crs(vnir))
Error in project(vnir[[3]], proj = crs(vnir)) : xy not numeric
```
I confirm that both rectify() and project() work in terra.

Is raster::rectify() going to be fixed? Not a big deal, I'm transitioning to terra.

**Comment by rhijmans** [comment] 2020-11-07 23:45
Fixing it in raster is not a priority for me

**Closed by rhijmans** 2020-11-07 23:45 UTC
